version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    ports:
      - "8008:8008"  
      - "8448:8448"  
    volumes:
      - ./data:/data  # homeserver文件的本地路径映射到容器路径
    environment:
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=synapse
      - SYNAPSE_REPORT_STATS=no  # 关闭报告统计信息
      - SYNAPSE_DB_HOST=db  # 指定数据库主机名为db
      - SYNAPSE_DB_USER=synapse_user  # 指定数据库用户名为synapse_user
      - SYNAPSE_DB_NAME=synapse  # 指定数据库名称为synapse
      - SYNAPSE_DB_PASSWORD=your_password  # 指定数据库密码
    depends_on:
      - db  # 确保在启动Synapse容器之前启动数据库容器
    networks:
      - matrix_net
    #command: generate

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=synapse  # 指定数据库名称为synapse
      - POSTGRES_USER=synapse_user  # 指定数据库用户名为synapse_user
      - POSTGRES_PASSWORD=your_password  # 指定数据库密
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # 将数据库数据目录映射到本地目录
    ports:
      - "5412:5432"  # PostgreSQL默认端口
    networks:
      - matrix_net

  synapse-generic-worker-1:
    image: matrixdotorg/synapse:latest
    container_name: synapse-generic-worker-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-generic-worker-1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./data:/data:rw # Replace VOLUME_PATH with the path to your Synapse volume
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    # Expose port if required so your reverse proxy can send requests to this worker
    # Port configuration will depend on how the http listener is defined in the worker configuration file
    ports:
      - 8081:8081
    depends_on:
      - synapse

  synapse-federation-sender-1:
    image: matrixdotorg/synapse:latest
    container_name: synapse-federation-sender-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-federation-sender-1.yaml"]
    healthcheck:
      disable: true
    networks:
      - matrix_net
    volumes:
      - ./data:/data:rw # Replace VOLUME_PATH with the path to your Synapse volume
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender
    depends_on:
      - synapse

  redis:
    image: redis:6-alpine
    networks:
      - matrix_net

networks:
  matrix_net:
    external: true


