version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "3.2"
          memory: 2048M
    ports:
      - "8008:8008"
      - "8448:8448"
    volumes:
      - ./synapse:/data:rw 
    environment:
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=synapse
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_DB_HOST=synapse_db
      - SYNAPSE_DB_USER=synapse_user
      - SYNAPSE_DB_NAME=synapse
      - SYNAPSE_DB_PASSWORD=your_password
    networks:
      - matrix_net_swarm
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8008/_matrix/static/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  synapse_db:
    image: postgres:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "3.2"
          memory: 2048M
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./synapse_db/pgsql_db:/var/lib/postgresql/data:rw 
      - ./synapse_db/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5412:5432"
    networks:
      - matrix_net_swarm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user"]
      interval: 10s
      timeout: 5s
      retries: 5


  synapse-generic-worker-1:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-generic-worker-1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net_swarm
    volumes:
      - ./synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 8081:8081

  synapse-generic-worker-2:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-generic-worker-2.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8082/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net_swarm
    volumes:
      - ./synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 8082:8082

  media_repo:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/media_repo.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8083/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net_swarm
    volumes:
      - ./synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.media_repository
    ports:
      - 8083:8083

  synapse-federation-reader-1:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "3.2"
          memory: 2048M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-federation-reader-1.yaml"]
    networks:
      - matrix_net_swarm
    volumes:
      - ./synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.federation_reader
    ports:
      - 8085:8085

  synapse-federation-sender-1:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "3.2"
          memory: 2048M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/synapse-federation-sender-1.yaml"]
    networks:
      - matrix_net_swarm
    volumes:
      - ./synapse:/data:rw 
    ports:
      - 8086:8086
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender

  push_worker:
    image: matrixdotorg/synapse:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/push_worker.yaml"]
    volumes:
      - ./synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.pusher
    networks:
      - matrix_net_swarm

  redis:
    image: redis:6-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "3"
          memory: 1024M
    networks:
      - matrix_net_swarm
    command: redis-server --appendonly yes --databases 16
    volumes:
      - ./redis_data:/data

networks:
  matrix_net_swarm:
    external: true