services:
  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    image: awesometechnologies/synapse-admin:latest
    ports:
      - "8079:80"
    networks:
      - matrix_net
    restart: unless-stopped

  element-web:
    image: vectorim/element-web:develop
    restart: unless-stopped
    ports:
      - 8070:80
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80/version || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./element-web/config.json:/app/config.json

networks:
  matrix_net:
    external: true